### ISSUE TITLE
Send interval not stored

### ISSUE THREAD

**Issue by emarvegt** [romix123/P1-wifi-gateway#4]
The measuring interval is not stored: when entering a value in the setup, saving and waiting for the restart, the value is not displayed and the actual send interval is 1s, as seen by the MQTT destination receiving all values every second.
In addition, the ESP webserver and data transmission stop working after a few hours and requiring a reboot, which may be related (some overflow or out of memory due to the frequent measuring/sending?).

![screencapture-192-168-178-107-Setup-2022-12-24-10_32_27](https://user-images.githubusercontent.com/32895221/209430088-563af79f-d59b-42e2-a44b-054c8b13ab62.png)

**Comment by romix123** [comment]
Ben er mee bezig.
Er komt een grote update deze week.

Verstuurd vanaf mijn iPad

**Comment by emarvegt** [comment]
De send interval lijkt nog steeds niet opgeslagen te worden in versie s. Bovendien wordt nu de opgeslagen SSID afgekapt na 8 karakters, dus kan hij geen verbinding maken met mijn netwerk met 16 of meer karakters.
